{% set name = "laszip" %}
{% set version = "2.1.0_isis7" %}
{% set sha256 = "9740d5fa081eb0002d502c484494778a3a1771aa5ceeb8493fbd3465ae6db731" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: laszip-src-{{ version }}.tar.gz
  url: http://download.osgeo.org/laszip/laszip-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win and py!=36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake 3.14.5
  host:
  run:
test:
  commands:
    - test -d $PREFIX/include/laszip  # [not win]
    - if not exist %LIBRARY_INC%\\laszip exit 1  # [win]

about:
  home: https://www.laszip.org
  license: LGPL-2.0
  license_family: LGPL
  license_file: COPYING
  summary: 'LASzip is a compression library for compressing ASPRS LAS format'
  description: |
    Quickly turns bulky LAS files into compact LAZ files without information loss.
  doc_url: https://www.laszip.org/
  dev_url: https://github.com/LASzip/LASzip

extra:
  recipe-maintainers:
    - chambbj
    - hobu
